[tools]
"cargo:bat" = "0.26"
"cargo:eza" = "0.23.4"
"cargo:git-delta" = "0.19"
"cargo:ripgrep" = "15.1"
"cargo:zoxide" = "0.9"
fzf = "0.73.1"
lazygit = "0.61"
neovim = "0.12.3"
node = "26.3.0"
pi = "0.79.6"
rust = "1.96.0"
zellij = "0.44.3"
zig = "0.16.0"
zola = "0.19"
